site_name: Bill's Public Notebook
site_url: https://xzbill.top/note
repo_name: zhaoxu98/note
repo_url: https://github.com/zhaoxu98/note
# edit_uri: main/docs
site_description: Bill的笔记本
copyright: Copyright &copy; 2023 <a href="https://github.com/zhaoxu98" target="_blank" rel="noopener">Bill Hsu</a>

